### ISSUE TITLE
An http-parser update broke etherpad

### ISSUE THREAD

**Issue by rgarrigue** [nodejs/http-parser#504] opened 2020-04-01 14:29 UTC
Hi there

We're running a SoftwareFactory, a packaging of OpenStack Zuul including an etherpad. On CentOS 7 64. A yum update this morning broke etherpad : we had empty reply from the NodeJS process itself. It did work without HTTP header (like using netcat only). Looking at the update log, we tried downgrading http-parser. Then etherpad service restart. It fixed the issue.

Here are the versions

    CentOS Linux release 7.7.1908 (Core)
    node: v8.9.4
    etherpad: 1.7.5

http-parser:

    The broken version : http-parser-2.7.1-8.el7_7.2.x86_64
    The functional version after downgrade : http-parser-2.7.1-8.el7.x86_64

This is a duplicate of https://github.com/ether/etherpad-lite/issues/3815

**Comment by sam-github** [comment] 2020-04-01 14:38
Could you provide a more complete bug report?

This doesn't have any reproduction information.

It also doesn't have any troubleshooting information. Is etherpad written in Node? What's the client? you ran netcat? What was its output?

Note that you are using an EOL node.js version, and a non-standard build (its not using the builtin http-parser), and an older release of http-parser.

**Comment by ploxiln** [comment] 2020-04-01 23:01
this looks like a duplicate of #500 (it's pretty much a centos packaging issue)

**Comment by bnoordhuis** [comment] 2020-04-02 08:35
I agree. I'm going to close this out as inactionable on multiple fronts (old node, old http-parser, in both cases not using an upstream version.)

**Closed by bnoordhuis** 2020-04-02 08:35 UTC

**Comment by rgarrigue** [comment] 2020-04-02 08:37
Agreed. My problem was solved by the downgrade to begin with, I'm aware that I'm not running latest versions. Opening the issue was mostly about signaling it here and there for people search to hit some result. Sorry, I should have said this to begin with.
