### ISSUE TITLE
Question: parsing response to HEAD request

### ISSUE THREAD

**Issue by socketpair** [nodejs/http-parser#291] opened 2016-03-08 19:29 UTC
When response on HEAD request is parsed, parser must ignore entity-body fields like transfer-encoding and content-length. So, two parsers (for requests and for responses) should work together. Moreover, since http-pipelining may be used, it is not so easy to implement parsing of http stream.

Also, "100 continue" complicates matching between requests and responses.

Next, "408 request timeout" response may happen while request just sent "HEA" and after big pause, "D …". So response body of 408 may or may not be protocol error (race condition in order of packets in tcp between streams)

And so on. There are many interesting cases in http.

What can you say about all that in http-parser?

**Comment by indutny** [comment] 2016-03-09 19:33
This is handled by:

```
 * The one exception is on_headers_complete. In a HTTP_RESPONSE parser
 * returning '1' from on_headers_complete will tell the parser that it
 * should not expect a body. This is used when receiving a response to a
 * HEAD request which may contain 'Content-Length' or 'Transfer-Encoding:
 * chunked' headers that indicate the presence of a body.
```

Basically, user code should return `1` or `0` depending on request type and any other things.

IMO, this is by design decision. (Won't fix)

**Closed by indutny** 2016-03-09 19:33 UTC
